# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/job_applications/migrations/0001_initial.py

# Generated by Django 6.0.2 on 2026-02-07 18:45

import apps.common.uuid
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('job_application_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('technical_test', 'Technical test'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='jobs.jobopportunity')),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='jobs.jobposting')),
            ],
            options={
                'db_table': 'job_application',
            },
        ),
    ]
