# backend/Dockerfile.dev

FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1 \
  VIRTUAL_ENV=/app/.venv \
  PATH="/app/.venv/bin:$PATH"

WORKDIR /app

RUN apt-get update && apt-get install -y \
  --no-install-recommends \
  libpq-dev \
  && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.11.8 /uv /usr/local/bin/uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-cache --group dev

COPY job_trackr ./job_trackr

COPY entrypoint_dev.sh /entrypoint_dev.sh
RUN chmod +x /entrypoint_dev.sh
CMD ["/entrypoint_dev.sh"]
