# backend/docker/job-ingestion/Dockerfile.dev

FROM python:3.12-slim

# ---- system deps ----
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# ---- copy dependency files ----
COPY pyproject.toml uv.lock ./

# ---- install uv ----
RUN pip install --upgrade pip \
    && pip install uv

# ---- export lockfile to requirements and install with pip ----
RUN uv export --format requirements-txt > requirements.txt \
    && pip install --no-cache-dir -r requirements.txt

# ---- copy source ----
COPY job_ingestion ./job_ingestion

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "job_ingestion.app.main:app", "--host","0.0.0.0", "--port","8000", "--reload", "--reload-dir","/app/job_ingestion"]
