# docker-compose.dev.yml

services:
  job-ingestion:
    container_name: job-ingestion-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
      - "5678:5678"
      - "5679:5679"
    env_file:
      - ./env/.env
    volumes:
      # hot reload: edit locally, container sees changes
      - ./app:/app
    restart: unless-stopped

volumes:
  pg_ingestion_dev_data:
