# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0001_initial.py

# Generated by Django 6.0.2 on 2026-02-27 09:49

import apps.common.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity_key', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'db_table': 'job_opportunity',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('opportunity_key',), name='uq_job_opo_key')],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('raw_url', models.URLField(max_length=2000)),
                ('platform', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2000)),
                ('job_key', models.CharField(blank=True, max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('easy_apply', models.BooleanField(default=False)),
                ('active_hiring', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting_fingerprint', models.CharField(editable=False, max_length=64)),
                ('job_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='jobs.jobopportunity')),
            ],
            options={
                'db_table': 'job_posting',
                'constraints': [models.UniqueConstraint(fields=('posting_fingerprint',), name='uq_job_posting_fp')],
            },
        ),
    ]
