# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0001_initial.py

# Generated by Django 6.0.4 on 2026-05-17 15:48

import apps.common.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('description', models.TextField(blank=True)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('easy_apply', models.BooleanField(default=False)),
                ('active_hiring', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('wttj', 'Welcome to the jungle'), ('career_page', 'Career page'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('fixed_term', 'Fixed-term'), ('freelance', 'Freelance'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('work_mode', models.CharField(choices=[('on_site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_posting',
                'ordering': ['-posted_at', '-created_at'],
                'indexes': [models.Index(fields=['platform'], name='idx_job_post_platform'), models.Index(fields=['easy_apply'], name='idx_job_post_easy'), models.Index(fields=['active_hiring'], name='idx_job_post_active'), models.Index(fields=['posted_at'], name='idx_job_post_posted'), models.Index(fields=['company'], name='idx_job_post_company')],
            },
        ),
    ]
