# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0001_initial.py

# Generated by Django 6.0.4 on 2026-08-21 15:41

import apps.common.uuid
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('description', models.TextField(blank=True)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('easy_apply', models.BooleanField(default=False)),
                ('active_hiring', models.BooleanField(default=False)),
                ('posted_on', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('wttj', 'Welcome to the jungle'), ('career_page', 'Career page')], max_length=50)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('fixed_term', 'Fixed-term'), ('freelance', 'Freelance')], max_length=50)),
                ('work_mode', models.CharField(blank=True, choices=[('on_site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_posting',
                'ordering': ['-posted_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCandidacy',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('technical_test', 'Technical test'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=50)),
                ('applied_on', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidacy', to='jobs.jobposting')),
            ],
            options={
                'verbose_name': 'job candidacy',
                'verbose_name_plural': 'job candidacies',
                'db_table': 'job_candidacy',
                'ordering': ['-applied_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['platform'], name='idx_job_post_platform'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['easy_apply'], name='idx_job_post_easy'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['active_hiring'], name='idx_job_post_active'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['posted_on'], name='idx_job_post_posted'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company'], name='idx_job_post_company'),
        ),
        migrations.AddIndex(
            model_name='jobcandidacy',
            index=models.Index(fields=['status'], name='idx_job_cand_status'),
        ),
        migrations.AddIndex(
            model_name='jobcandidacy',
            index=models.Index(fields=['applied_on'], name='idx_job_cand_applied'),
        ),
    ]
