# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0002_add_identity_fields.py

# Generated by Django 6.0.2 on 2026-03-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobposting',
            name='uq_job_posting_platform_job_key',
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='opportunity_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posting_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='jobs.jobopportunity'),
        ),
    ]
