# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0002_add_candidacy.py

# Generated by Django 6.0.4 on 2026-05-17 15:50

import apps.common.uuid
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCandidacy',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('technical_test', 'Technical test'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=50)),
                ('applied_on', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidacy', to='jobs.jobposting')),
            ],
            options={
                'db_table': 'job_candidacy',
                'ordering': ['-applied_on', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_job_cand_status'), models.Index(fields=['applied_on'], name='idx_job_cand_applied')],
            },
        ),
    ]
