# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0003_add_candidacy_verbose_names.py

# Generated by Django 6.0.4 on 2026-05-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_candidacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcandidacy',
            options={'ordering': ['-applied_on', '-created_at'], 'verbose_name': 'job candidacy', 'verbose_name_plural': 'job candidacies'},
        ),
    ]
