# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0003_backfill_identity_fields.py

# Generated by Django 6.0.2 on 2026-03-01 11:04

from django.db import migrations, transaction

import re
import unicodedata
import hashlib
import json
from urllib.parse import urlparse, urlunparse


def normalize_text(value: str | None) -> str | None:
    if value is None:
        return None

    # Remove leading and trailing whitespaces
    value = value.strip()

    # Convert to lowercase
    value = value.lower()

    # Normalize accents (é → e)
    value = unicodedata.normalize("NFKD", value)
    value = value.encode("ascii", "ignore").decode("ascii")

    # Collapse whitespace to single space
    value = re.sub(r"\s+", " ", value)

    # Keep only semantic punctuation and symbols
    value = re.sub(r"[^\w\s+#./&-]", "", value)

    # Empty string and None produce same result
    if value == "":
        return None

    return value


def normalize_url(value: str | None) -> str | None:
    if value is None:
        return None

    value = value.strip()
    if not value:
        return None

    parsed = urlparse(value)

    # Normalize scheme + netloc to lowercase
    scheme = parsed.scheme.lower()
    netloc = parsed.netloc.lower()

    # Remove trailing slash from path
    path = parsed.path.rstrip("/")

    normalized = parsed._replace(
        scheme=scheme,
        netloc=netloc,
        path=path,
    )

    return urlunparse(normalized)


OPPORTUNITY_KEY_VERSION = 1
def compute_opportunity_key(
    *,
    title: str,
    company: str,
    location: str | None,
) -> str:
    """
    Compute a stable deterministic key for grouping
    multiple JobPostings into one JobOpportunity.

    Semantics:
    - Case/whitespace/punctuation-insensitive via normalize_text
    - Missing location values are treated consistently via normalize_text
    - Uses JSON encoding to avoid delimiter collisions

    Versioned to allow future evolution.
    """

    payload = [
        OPPORTUNITY_KEY_VERSION,
        normalize_text(title),
        normalize_text(company),
        normalize_text(location),
    ]

    base = json.dumps(
        payload,
        separators=(",", ":"),
        ensure_ascii=False,
    )

    return hashlib.sha256(base.encode("utf-8")).hexdigest()


def backfill_opportunity_key(apps, schema_editor):
    JobOpportunity = apps.get_model("jobs", "JobOpportunity")

    with transaction.atomic():
        batch = []
        for obj in JobOpportunity.objects.iterator(chunk_size=1000):
            if obj.opportunity_key is None:
                obj.opportunity_key = compute_opportunity_key(
                    title=obj.title,
                    company=obj.company,
                    location=obj.location
                )
                batch.append(obj)

            if len(batch) >= 1000:
                JobOpportunity.objects.bulk_update(batch, ["opportunity_key"])
                batch.clear()

        if batch:
            JobOpportunity.objects.bulk_update(batch, ["opportunity_key"])


def compute_fingerprint(
    *,
    platform: str,
    job_key: str | None,
    canonical_url: str | None,
    title: str,
    company: str,
    location: str | None,
) -> str:
    """
    Compute a stable, deterministic fingerprint for job deduplication.

    - Text fields are normalized via normalize_text
    - URL fields are normalized via normalize_url
    - None and empty strings are treated equivalently for all fields
    - Uses unambiguous JSON encoding to avoid delimiter collisions
    """

    payload = [
        normalize_text(platform),
        normalize_text(job_key),
        normalize_url(canonical_url),
        normalize_text(title),
        normalize_text(company),
        normalize_text(location),
    ]

    base = json.dumps(
        payload,
        separators=(",", ":"),
        ensure_ascii=False,
    )

    return hashlib.sha256(base.encode("utf-8")).hexdigest()


def backfill_posting_fingerprint(apps, schema_editor):
    JobPosting = apps.get_model("jobs", "JobPosting")

    with transaction.atomic():
        batch = []
        for obj in JobPosting.objects.iterator(chunk_size=1000):
            if obj.posting_fingerprint is None:
                obj.posting_fingerprint = compute_fingerprint(
                    platform=obj.platform,
                    job_key=obj.job_key,
                    canonical_url=obj.canonical_url,
                    title=obj.title,
                    company=obj.company,
                    location=obj.location,
                )
                batch.append(obj)

            if len(batch) >= 1000:
                JobPosting.objects.bulk_update(batch, ["posting_fingerprint"])
                batch.clear()

        if batch:
            JobPosting.objects.bulk_update(batch, ["posting_fingerprint"])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_identity_fields'),
    ]

    operations = [
        migrations.RunPython(
            backfill_opportunity_key,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_posting_fingerprint,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
