# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0004_detect_identity_collisions.py

# Generated by Django 6.0.2 on 2026-03-05 15:35

from django.db import migrations, models


def assert_no_opportunity_collisions(apps, schema_editor):
    JobOpportunity = apps.get_model("jobs", "JobOpportunity")

    duplicates = (
        JobOpportunity.objects
        .filter(opportunity_key__isnull=False)
        .values("opportunity_key")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )

    if duplicates.exists():
        raise RuntimeError(
            "Duplicate opportunity_key values detected.\n"
            "Resolve duplicates before applying the unique constraint."
        )


def assert_no_posting_collisions(apps, schema_editor):
    JobPosting = apps.get_model("jobs", "JobPosting")

    duplicates = (
        JobPosting.objects
        .filter(posting_fingerprint__isnull=False)
        .values("posting_fingerprint")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )

    if duplicates.exists():
        raise RuntimeError(
            "Duplicate posting_fingerprint values detected.\n"
            "Resolve duplicates before applying the unique constaint."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_backfill_identity_fields'),
    ]

    operations = [
        migrations.RunPython(assert_no_opportunity_collisions),
        migrations.RunPython(assert_no_posting_collisions),
    ]
