# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0004_blank_charfield_textchoices.py

# Generated by Django 6.0.4 on 2026-06-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_candidacy_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('fixed_term', 'Fixed-term'), ('freelance', 'Freelance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='platform',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('wttj', 'Welcome to the jungle'), ('career_page', 'Career page')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('on_site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=50),
        ),
    ]
