# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0005_rename_posted_at_field_posted_on.py

# Generated by Django 6.0.4 on 2026-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_blank_charfield_textchoices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-posted_on', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='jobposting',
            name='idx_job_post_posted',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['posted_on'], name='idx_job_post_posted'),
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='posted_at',
        ),
    ]
