# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0005_add_unique_constraints.py

# Generated by Django 6.0.2 on 2026-03-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_detect_identity_collisions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobopportunity',
            constraint=models.UniqueConstraint(fields=('opportunity_key',), name='uq_job_opo_key'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(fields=('posting_fingerprint',), name='uq_job_posting_fp'),
        ),
    ]
