# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0006_make_identity_fields_not_null.py

# Generated by Django 6.0.2 on 2026-03-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_add_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='opportunity_key',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posting_fingerprint',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
