# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0007_remove_url_add_description.py

# Generated by Django 6.0.2 on 2026-03-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_make_identity_fields_not_null'),
    ]

    operations = [
        # NOTE:
        # `JobOpportunity.url` was a legacy field from an early
        # prototype. URLs now belong to `JobPosting` objects.
        # No data migration is required before removing the column.
        migrations.RemoveField(
            model_name='jobopportunity',
            name='url',
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='description',
            # Provide a temporary default so the migration succeeds if rows already exist.
            # `preserve_default=False` ensures the default is used only during the
            # migration and is not kept as a permanent database default.
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
