# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0007_remove_url_add_description.py

# Generated by Django 6.0.2 on 2026-03-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_make_identity_fields_not_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopportunity',
            name='url',
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
