# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/jobs/migrations/0009_add_query_indexes.py

# Generated by Django 6.0.2 on 2026-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobposting_ordering'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['platform'], name='idx_job_post_platform'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['easy_apply'], name='idx_job_post_easy'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['active_hiring'], name='idx_job_post_active'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['posted_at'], name='idx_job_post_posted'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company'], name='idx_job_post_company'),
        ),
    ]
