# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/ingestion/migrations/0001_initial.py

# Generated by Django 6.0.2 on 2026-02-07 18:42

import apps.common.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedJobPosting',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('raw_url', models.URLField(max_length=2000)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('job_key', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('easy_apply', models.BooleanField(blank=True, null=True)),
                ('active_hiring', models.BooleanField(blank=True, null=True)),
                ('ingestion_source', models.CharField(choices=[('email', 'Email'), ('api', 'API'), ('webhook', 'Webhook')], default='email', help_text='How the job entered the system, example: email, api, ...', max_length=50)),
                ('source_event_id', models.CharField(blank=True, help_text='Message ID, webhook ID, or batch ID', max_length=255, null=True)),
                ('fingerprint', models.CharField(help_text='Hash used for deduplication', max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingested_job_posting',
                'indexes': [models.Index(fields=['platform', 'job_key'], name='idx_ing_job_plat_key'), models.Index(fields=['status', 'ingested_at'], name='idx_ing_job_status_ts')],
                'constraints': [models.UniqueConstraint(fields=('fingerprint',), name='uniq_ing_job_fp')],
            },
        ),
    ]
