# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/ingestion/migrations/0001_initial.py

# Generated by Django 6.0.1 on 2026-01-26 16:15

import apps.ingestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestedJobPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.ingestion.models.uuid7_default,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                (
                    "source_event_id",
                    models.CharField(
                        blank=True,
                        help_text="Message ID, webhook ID, or batch ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("duplicate", "Duplicate"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_url", models.URLField()),
                ("canonical_url", models.URLField(blank=True, null=True)),
                ("job_key", models.CharField(blank=True, max_length=255, null=True)),
                ("platform", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("salary", models.CharField(blank=True, max_length=255, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="Hash used for deduplication", max_length=64
                    ),
                ),
            ],
            options={
                "db_table": "ingested_job_posting",
                "indexes": [
                    models.Index(
                        fields=["fingerprint"], name="ingested_jo_fingerp_e1319f_idx"
                    ),
                    models.Index(
                        fields=["platform", "job_key"],
                        name="ingested_jo_platfor_ba7409_idx",
                    ),
                ],
            },
        ),
    ]
