# SPDX-License-Identifier: AGPL-3.0-or-later
# File: backend/job_trackr/apps/ingestion/migrations/0002_add_fk_fields.py

# Generated by Django 6.0.2 on 2026-03-04 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('jobs', '0006_make_identity_fields_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestedjobposting',
            name='job_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingested_rows', to='jobs.jobopportunity'),
        ),
        migrations.AddField(
            model_name='ingestedjobposting',
            name='job_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingested_rows', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='ingestedjobposting',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
